name: Deploy to Firebase
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  main:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jsryudev/deploy-firebase-functions@v20.0.1
        env:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PDF_CRAFT_DEV }}
          projectId: pdf-craft-dev
          FUNCTIONS_DIR: functions
